define(function () {
    return [
        {
            title:'主页',
            icon:'fa-home',
            id:'',
            nodes:[
                {
                    title:'Dashboard1',
                    funUrl:'/app-demo-chart',
                    id:'',
                    nodes:[
                        {
                            funUrl:'app-demo-chart',
                            id:'app-demo-chart',
                            title:'charts'
                        }
                    ]
                },{
                    title:'Dashboard2',
                    funUrl:'/app-charts',
                    id:'',
                    nodes:[
                        {
                            funUrl:'app-charts',
                            id:'app-charts',
                            title:'chartsdemo'
                        }
                    ]
                },
                {
                    title:'Dashboard3',
                    funUrl:'/app-echarts',
                    id:'',
                    nodes:[
                        {
                            funUrl:'app-echarts',
                            id:'app-echarts',
                            title:'EchartsDemo'
                        }
                    ]

                }
            ]
        },
        {
            title:'表单',
            icon:'fa-edit',
            id:'',
            nodes:[
                {
                    title:'常规表单',
                    funUrl:'/app-demo-form',
                    id:'',
                    nodes:[
                        {
                            funUrl:'app-general-form',
                            id:'app-general-form',
                            title:'常规表单'
                        }
                    ]
                },{
                    title:'高级组件',
                    funUrl:'/app-advanced-form',
                    id:'',
                    nodes:[
                        {
                            funUrl:'app-advanced-form',
                            id:'app-advanced-form',
                            title:'高级表单组件'
                        }
                    ]
                },{
                    title:'通讯录表单',
                    funUrl:'/app-grid',
                    id:'',
                    nodes:[
                        {
                            funUrl:'app-info',
                            id:'app-info',
                            title:'通信录'
                        }
                    ]
                },{
                    title:'流程表单',
                    funUrl:'/app-form-wizard',
                    id:'',
                    nodes:[
                        {
                            title:'流程',
                            funUrl:'app-form-wizard',
                            id:'app-form-wizard'
                        }
                    ]
                },{
                    title:'上传表单',
                    funUrl:'/app-form-upload',
                    id:'',
                    nodes:[
                        {
                            title:'上传图片',
                            funUrl:'app-form-upload',
                            id:'app-form-upload'
                        }
                    ]
                },{
                    title:'按钮表单',
                    funUrl:'',
                    id:'',
                    nodes:[
                        {
                            title:'按钮组',
                            funUrl:'app-form-button',
                            id:'app-form-button'
                        }
                    ]
                }
            ]
        },
        {
            title:'UI元素',
            icon:'fa-desktop',
            id:'',
            nodes:[
                {
                    title:'常规元素',
                    funUrl:'',
                    path:'/app-general-elements',
                    id:'',
                    nodes:[
                        {
                            title:'常规元素组件',
                            funUrl:'app-general-elements',
                            id:'app-general-elements',
                        }
                    ]
                },{
                    title:'媒体相册',
                    funUrl:'/app-media-gallery',
                    id:'',
                    nodes:[
                        {
                            title:'相册demo',
                            funUrl:'app-media-gallery',
                            id:'app-media-gallery',
                        }
                    ]
                },{
                    title:'图标',
                    funUrl:'',
                    path:'/app-icons',
                    id:'',
                    nodes:[
                        {
                            title:'常用图标',
                            funUrl:'app-icons',
                            id:'app-icons'
                        }
                    ]

                },{
                    title:'Glyphicons',
                    funUrl:'',
                    path:'/app-glyphicons',
                    id:'',
                    nodes:[
                        {
                            title:'常用字体图标',
                            funUrl:'app-glyphicons',
                            id:'app-glyphicons'
                        }
                    ]

                },{
                    title:'窗口小部件',
                    funUrl:'/app-widgets',
                    id:'',
                    nodes:[
                        {
                            title:'各种小部件',
                            funUrl:'app-widgets',
                            id:'app-widgets'
                        }
                    ]

                },{
                    title:'日历',
                    funUrl:'/app-home',
                    id:'',
                    nodes:[
                        {
                            title:'日历列表',
                            funUrl:'app-home',
                            id:'app-home',
                        }
                    ]

                }
            ]
        },
        {
            title:'表格',
            icon:'fa-table',
            id:'',
            nodes:[
                {
                    title:'表格组',
                    funUrl:'/app-tables',
                    id:'',
                    nodes:[
                        {
                            title:'常规表格类型',
                            funUrl:'app-tables',
                            id:'app-tables'
                        }
                    ]
                },{
                    title:'动态表格',
                    funUrl:'/app-table-dynamic',
                    id:'',
                    nodes:[
                        {
                            title:'动态表格类型',
                            funUrl:'app-table-dynamic',
                            id:'app-table-dynamic'
                        }
                    ]
                }
            ]
        },
        {
            title:'传统页面',
            icon:'fa-bug',
            id:'',
            nodes:[
                {
                    title:'Project',
                    funUrl:'/app-project-track',
                    id:'',
                    nodes:[
                        {
                            funUrl:'app-project-track',
                            id:'app-project-track',
                            title:'项目内容'
                        }
                    ]
                },{
                    title:'ProjectDetail',
                    funUrl:'/app-project-detail',
                    id:'',
                    nodes:[
                        {
                            funUrl:'app-project-detail',
                            id:'app-project-detail',
                            title:'项目详情'
                        }
                    ]
                }
            ]
        },
        {
            title:'额外页面',
            icon:'fa-windows',
            id:'',
            nodes:[
                {
                    title:'定价卡片设计',
                    funUrl:'/app-pricing-design',
                    id:'',
                    nodes:[
                        {
                            funUrl:'app-pricing-design',
                            id:'app-pricing-design',
                            title:'定价卡片'
                        }
                    ]

                }
            ]
        }
    ]
})