define([
/*    'modules/appContent',
    'modules/appDemoForm',
    'modules/appDemoForm/elementForm',
    'modules/appDemoTable',
    'modules/appDemoChart',
    'modules/appProjectTrack',
    'modules/appHome',
    'modules/appInfo',
    'modules/appGrid',*/
    'modules/arcgisPlugin',
    'modules/appUnknown',
 /*   'modules/appGeneralForm',
    'modules/appFormWizard',
    'modules/appFormUpload',
    'modules/appFormButton',
    'modules/appTables',
    'modules/appAdvancedForm',
    'modules/appGeneralElements',
    'modules/appIcons',
    'modules/appGlyphicons',
    'modules/appTableDynamic',
    'modules/appPricingDesign',
    'modules/appCharts',
    'modules/appMorris',
    'modules/appProjectDetail',
    'modules/appMediaGallery',
    'modules/appWidgets',
    'modules/appEcharts',
    'modules/appTruck/truck',*/
    /*   'modules/appCaseManager/disposeDepartment',
  //  'modules/appCaseManager/caseManager',

    'modules/appInterfaceTest',
*/
    'modules/appSys/dict',
    'modules/appFacilityManager/facilityType',
    'modules/appFacilityManager/facilityManager',
/*    'modules/appDemo1/companyDemo',
    'modules/appDemo1/companyDemoExt',
    'modules/appDemo1/treeDemo',
    'modules/appDemo1/treeDemoExt',
    'modules/appAlarmManager/alarmType',
    'modules/appAlarmManager/alarm',*/
    'modules/appIotDeviceManager/iotDevice',
    'modules/appIotDeviceManager/iotDeviceType',
    'modules/appIotDeviceManager/iotPlatformDevice',
    'modules/facilityManageGraph',
    'modules/appIotDeviceManager/deviceCommand',
    'modules/appIotDeviceManager/eiotMaintenance',
    'modules/emergencyRescue',
    'modules/appSys/syslog',
    'modules/appIotDeviceManager/monitorUser',
    'modules/auth/userManager',
    'modules/auth/roleManager',
    'modules/auth/menuManager',
    'modules/auth/orgManager',
    'modules/map/layerManager',
    'modules/map/projectManager',
    'modules/map/dataRoleManager',
    'modules/se/serviceRouterManager',
    'modules/se/seServiceManager',
    'modules/se/roleServiceManager',
    'modules/se/serviceLogManager',
    'modules/se/serviceInvokeCountStats',
    'modules/se/serviceUserInvokeCountStats',
    'modules/se/userServiceInvokeCountStats',
    'modules/se/networkEnvironmentManager',
    'modules/se/userServiceManager',
    'modules/se/currentUserServiceManager',
    'modules/emergencyRescue/emergenCommand/dispatcheCenter',
    'modules/appFacilityManager/facilityTypeRoleManager',
    'modules/appFacilityManager/dataRoleFacilityManager',
    'modules/onlineMonitor/statisticsPanel',
    'modules/onlineMonitor/facilityInfoTable',
    'modules/onlineMonitor/dataScreen',
    'modules/onlineMonitor/eLTEVideo'
], function (
 /*   appContent,
             appDemoForm,
             elementForm,
             appDemoTable,
             appDemoChart,
             appProjectTrack,
             appHome,
             appInfo,
             appGrid,*/
             arcgisPlugin,
            /* appUnknown,
             appGeneralForm,
             appFormWizard,
             appFormUpload,
             appFormButton,
             appTables,
             appAdvancedForm,
             appGeneralElements,
             appIcons,
             appGlyphicons,
             appTableDynamic,
             appPricingDesign,
             appCharts,
             appMorris,
             appProjectDetail,
             appMediaGallery,
             appWidgets,
             appEcharts,
             truck,
             disposeDepartment,*/
          //   caseManager,
             appInterfaceTest,
             dict,
             facilityType,
             facilityManage,
           /*  companyDemo,
             companyDemoExt,
             treeDemo,
             treeDemoExt,
             alarmType,
             alarm,*/
             iotDevice,
             iotDeviceType,
             iotPlatformDevice,
             facilityManageGraph,
             deviceCommand,
             eiotMaintenance,
             emergencyRescue,
             syslog,
             monitorUser,
             userManager,
             roleManager,
             menuManager,
             orgManager,
             layerManager,
             projectManager,
             dataRoleManager,
             serviceRouterManager,
             seServiceManager,
             roleServiceManager,
             serviceLogManager,
             serviceInvokeCountStats,
             serviceUserInvokeCountStats,
             userServiceInvokeCountStats,
             networkEnvironmentManager,
             userServiceManager,
             currentUserServiceManager,
             dispatcheCenter,
             facilityTypeRoleManager,
             dataRoleFacilityManager,
             statisticsPanel,
             facilityInfoTable,
             dataScreen,
             eLTEVideo) {
    return {
        'arcgis-plugin': arcgisPlugin,
      //  'caseManager': caseManager,
        'appInterfaceTest': appInterfaceTest,
        'dict': dict,
        'facilityType': facilityType,
        'facilityManager': facilityManage,
        'iotDevice': iotDevice,
        'iotDeviceType': iotDeviceType,
        'iotPlatformDevice': iotPlatformDevice,
        'facility-manage-graph': facilityManageGraph,
        'deviceCommand': deviceCommand,
        'eiotMaintenance': eiotMaintenance,
        'emergency-rescue': emergencyRescue,
        'syslog': syslog,
        'monitorUser': monitorUser,
        'userManager': userManager,
        'roleManager': roleManager,
        'menuManager': menuManager,
        'orgManager': orgManager,
        'layerManager': layerManager,
        'projectManager': projectManager,
        'dataRoleManager': dataRoleManager,
        'serviceRouterManager': serviceRouterManager,
        'seServiceManager': seServiceManager,
        'roleServiceManager': roleServiceManager,
        'serviceLogManager': serviceLogManager,
        'serviceInvokeCountStats': serviceInvokeCountStats,
        'serviceUserInvokeCountStats': serviceUserInvokeCountStats,
        'userServiceInvokeCountStats': userServiceInvokeCountStats,
        'networkEnvironmentManager': networkEnvironmentManager,
        'userServiceManager': userServiceManager,
        'currentUserServiceManager': currentUserServiceManager,
        'dispatche-center': dispatcheCenter,
        'facilityTypeRoleManager': facilityTypeRoleManager,
        'dataRoleFacilityManager': dataRoleFacilityManager,
        'statisticsPanel':statisticsPanel,
        'facility-info-table':facilityInfoTable,
        'dataScreen':dataScreen,
        'elte-video':eLTEVideo
    }
});